import { NAMED_COLORS, checkColor, isColorProp, suggestColor } from "../catalog/index.js"
import {
  attributeName,
  objectEntries,
  resolveObjectExpression,
  staticStrings,
} from "../project/jsx.js"
import { defineRule } from "../project/rule.js"
import type { Node } from "../project/types.js"

/**
 * OpenTUI's `parseColor()` understands 28 names plus hex. Everything else —
 * `slate`, `indigo`, `pink`, `rgb(34 197 94)`, `var(--accent)` — logs a warning
 * and returns **opaque magenta**.
 *
 * Nothing else surfaces it. `ColorInput` is `string | RGBA`, so the type
 * checker has no opinion, the app runs, and the only symptom is a magenta panel
 * that the person who wrote the code may never look at. For an agent editing a
 * TUI it never sees rendered, the failure is completely invisible.
 *
 * The palette is generated by probing the real `parseColor()` — see
 * `scripts/sync-catalog.ts` — so it tracks whatever version is installed.
 */
export default defineRule(
  {
    type: "problem",
    docs: {
      description: "Disallow color values OpenTUI silently renders as magenta.",
      url: "https://github.com/phall1/opentui-lint/blob/main/docs/rules/valid-colors.md",
    },
    schema: [
      {
        type: "object",
        properties: {
          props: {
            type: "array",
            items: { type: "string" },
            description: "Additional prop names whose values are colors.",
          },
        },
        additionalProperties: false,
      },
    ],
  },
  (context) => {
    const extraProps = new Set<string>((context.options[0]?.props as string[]) ?? [])
    const isColor = (name: string) => isColorProp(name) || extraProps.has(name)

    function check(propName: string, value: string, node: Node): void {
      const verdict = checkColor(value)
      if (verdict.kind === "ok") return

      const suggestion = suggestColor(value)
      const fallback = `Use a hex string such as "#22c55e", or one of: ${NAMED_COLORS.join(", ")}.`

      const explanation =
        verdict.kind === "css-function"
          ? `parseColor() does not support CSS color functions, so \`${verdict.fn}(…)\` resolves to opaque magenta.`
          : verdict.kind === "malformed-hex"
            ? `"${value}" is not a valid hex color, so it resolves to opaque magenta.`
            : `"${value}" is not one of OpenTUI's color names, so it resolves to opaque magenta.`

      context.report({
        node,
        message:
          `${propName}="${value}" will render magenta. ${explanation} ` +
          `This never fails typecheck — ColorInput is just \`string | RGBA\` — and at runtime it only warns. ` +
          (suggestion ? `Did you mean "${suggestion}"? ` : "") +
          (suggestion ? "" : fallback),
      })
    }

    /** Walks a `style={{ … }}` object, including one hoisted into a const. */
    function checkStyleObject(expression: Node | undefined): void {
      const object = resolveObjectExpression(context, expression)
      if (!object) return
      for (const entry of objectEntries(object)) {
        if (!isColor(entry.key)) continue
        for (const value of staticStrings(entry.valueNode)) check(entry.key, value, entry.valueNode)
      }
    }

    return {
      JSXAttribute(node) {
        const name = attributeName(node)
        if (!name) return

        if (name === "style") {
          const expression =
            node.value?.type === "JSXExpressionContainer" ? node.value.expression : undefined
          checkStyleObject(expression)
          return
        }

        if (!isColor(name)) return
        for (const value of staticStrings(node.value)) check(name, value, node.value ?? node)
      },
    }
  },
)
